POST http://localhost:4000/api/profile
Content-Type: application/json

{
    "userId": 2,
    "fullName": "naoexiste",
    "birthDate": "1990-01-01",
    "avatarUrl": "https://img.freepik.com/free-vector/smiling-young-man-illustration_1308-174669.jpg?semt=ais_incoming&w=740&q=80"
}
###

GET http://localhost:4000/api/profile/2

###

PUT http://localhost:4000/api/profile/2
Content-Type: application/json

{
    "fullName": "Nome AtualizadoOOOO",
    "birthDate": "1991-02-02",
    "avatarUrl": "https://img.freepik.com/free-vector/smiling-young-man-illustration_1308-174669.jpg?semt=ais_incoming&w=740&q=80"
}
